### ISSUE TITLE
#Affordances - Default graph on landing page

### ISSUE THREAD

**Issue by christopher-uber** [JosephGarrone/uq-parking-scraper#5]
Expected behaviour;
Graph shows all carparks so I know what carparking overall is like at UQ as I can move between carparks

Actual Result;
Defaults to one carpark - not obvious that a specific car park is being shown (title on the graph?)

**Comment by JosephGarrone** [comment]
Probably better to move all these requests to www.github.com/JosephGarrone/uq-parking-stats which is the web interface, the scraper solely deals with fetching the data.

**Comment by christopher-uber** [comment]
That makes a lot more sense - definitely throw that link in the readme

**Comment by christopher-uber** [comment]
(NB some of these I know you've already just recently done, so they're there that you can mark them "fixed")
